Creation of heat template for ELK stack
binerogroup/heat-templates pull request #2
Opened 2023-08-22 07:16 UTC by pranav79

2023-08-22 10:39 UTC, jain-rajat commented on services/ELK/elasticsearch-heat-template.yml
> +description: Elasticsearch
Improve description everwhere !

2023-08-22 10:39 UTC, jain-rajat commented on services/ELK/elasticsearch-heat-template.yml
> +    default: local
default does not look right ?

2023-08-22 10:39 UTC, jain-rajat commented on services/ELK/elasticsearch-heat-template.yml
> +    type: OS::Neutron::SecurityGroup
We have a predefined SG for Elastic search, can we use that , but the only con is that if someone deletes it?
@AndreasDilworth  any opinion?

2023-08-22 10:39 UTC, jain-rajat commented on services/ELK/elasticsearch-heat-template.yml
> +          - sudo systemctl start elasticsearch
Can we also hit a curl request to see ES is up and running !

2023-08-22 10:39 UTC, jain-rajat commented on services/ELK/kibana-heat-template.yml
> +        - get_resource: sec_ssh_kibana
We need to config Elasticsearch in Kibana to start showing logs,  that can be only done in GUI?

2023-08-22 10:39 UTC, jain-rajat commented on services/ELK/logstash-heat-template.yml
> +          - systemctl start logstash
Logstash will take log inputs from where ?

2023-08-22 11:40 UTC, pranav79 commented on services/ELK/logstash-heat-template.yml
> +          - systemctl start logstash
The Logstash setup and define log inputs, we would typically create Logstash configuration files in the /etc/logstash/conf.d/ directory on the logstash instance. These configuration files would specify the inputs, filters, and outputs for our specific use cases and as mentioned earlier,  we will have to manually configure logstash pipelines, inputs, filters and outputs after deploying of these machines.

2023-08-24 07:41 UTC, AndreasDilworth commented on services/ELK/elasticsearch-heat-template.yml
> +    default: local
There needs to be a default, but what it is is not important. This is OK.

2023-08-24 07:44 UTC, AndreasDilworth commented on services/ELK/elasticsearch-heat-template.yml
> +    type: OS::Neutron::SecurityGroup
Defining our own group is OK but I would use the same group as "remote group" as opposed to fully opening the port to everyone  - and pick a name that is more relevant to the ports usage - do you need this port for management? Is SSH the only port you might use for ES?

2023-08-24 08:10 UTC, AndreasDilworth commented on services/ELK/logstash-heat-template.yml
> +          - systemctl start logstash
See previous comment regarding documentation.

2023-08-24 08:15 UTC, AndreasDilworth commented on services/ELK/elasticsearch-heat-template.yml
> +          - sudo systemctl start elasticsearch
There are some examples of using WaitConditionHandle's https://github.com/binerogroup/heat-templates/blob/main/database/mariadb/mariadb.yaml#L275 for signaling to user when bootstrapping is completed.

2023-08-24 08:16 UTC, AndreasDilworth commented on services/ELK/logstash-heat-template.yml
> +  sec_ssh_logstash:
See previous comments on secgroups.

2023-08-24 08:18 UTC, AndreasDilworth commented on services/ELK/logstash-heat-template.yml
> +          delete_on_termination: true
Is this device storing user data? Might not want to do delete_on_termination.

Additionally, can we use the Mistral backup workflows here?

2023-08-24 08:23 UTC, AndreasDilworth reviewed
Are those templates all standalone? The idea is to provide the entire stack in one template, so you might want to merge those or use the "subtemplates" as a resource type

Example: https://github.com/binerogroup/heat-templates/blob/main/database/mariadb/mariadb.yaml#L340

2023-08-24 17:27 UTC, jain-rajat commented on services/ELK/elasticsearch-heat-template.yml
> +    type: OS::Neutron::SecurityGroup
oh right, @pranav79 22 is not the right port, we have predefined Security Group for SG - you can use that for ports which is required.

2023-12-07 11:16 UTC, AndreasDilworth reviewed
Most issues mentioned before are still here (just merged into a combined template).
Those still needs to be addressed - the idea is to provide an useful "production-like" starting configuration. Some things (like log ingestion settings) may be too specific to different use cases to provide a generic default - and that's fine, but we should set up default user accounts for logging on to the WebUI, setup storage/backup for databases etc.

If the separated templates are not supposed to be used - they should be removed from the PR.

2023-12-28 05:36 UTC, pranav79 commented on services/ELK/elasticsearch-heat-template.yml
> +description: Elasticsearch
Updated description for all templates.

2023-12-28 05:38 UTC, pranav79 commented on services/ELK/elasticsearch-heat-template.yml
> +    type: OS::Neutron::SecurityGroup
Used existing ports  that has been assigned for ELK. 
Existing ports were:
- bin-elasticsearch
- bin-kibana
- bin-logstash

2023-12-28 05:38 UTC, pranav79 commented on services/ELK/elasticsearch-heat-template.yml
> +          - sudo systemctl start elasticsearch
Updated.

2023-12-28 05:39 UTC, pranav79 commented on services/ELK/kibana-heat-template.yml
> +        - get_resource: sec_ssh_kibana
Will add these configuration changes that has to be carried after initial setup in README.

2023-12-28 05:39 UTC, pranav79 commented on services/ELK/logstash-heat-template.yml
> +          - systemctl start logstash
Will add these configuration changes that has to be carried after initial setup in README.

2023-12-28 05:39 UTC, pranav79 commented on services/ELK/logstash-heat-template.yml
> +  sec_ssh_logstash:
Updated with existing groups.

2023-12-28 05:40 UTC, pranav79 commented on services/ELK/logstash-heat-template.yml
> +          delete_on_termination: true
Set delete_on_termination to false and also creating a separate volume to store elasticsearch data.

2023-12-28 05:43 UTC, pranav79 commented on services/ELK/elasticsearch-heat-template.yml
> +heat_template_version: rocky
Updated.

2023-12-28 05:45 UTC, pranav79 commented on services/ELK/elasticsearch-heat-template.yml
> +          - wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
Using curl instead of apt-key add.
`sudo curl -sfL --output /usr/share/keyrings/elastic-gpg-key https://artifacts.elastic.co/GPG-KEY-elasticsearch`

2023-12-28 05:45 UTC, pranav79 commented on services/ELK/ELK-combined-heat-template.yml
> +          - wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
Updated.

2023-12-28 05:45 UTC, pranav79 commented on services/ELK/ELK-combined-heat-template.yml
> +          - sudo apt-get update
Removed sudo from here.

2023-12-28 05:46 UTC, pranav79 commented on services/ELK/ELK-combined-heat-template.yml
> +          remote_ip_prefix: 0.0.0.0/0
Updated with only ELK ports.

2023-12-28 05:46 UTC, pranav79 commented on services/ELK/ELK-combined-heat-template.yml
> +          remote_ip_prefix: 0.0.0.0/0
Updated with only ELK security groups.

2023-12-28 05:46 UTC, pranav79 commented on services/ELK/ELK-combined-heat-template.yml
> +          remote_ip_prefix: 0.0.0.0/0
Updated with only ELK security groups.

2023-12-28 05:46 UTC, pranav79 commented on services/ELK/ELK-combined-heat-template.yml
> +      size: 20
Updated.

2023-12-28 05:47 UTC, pranav79 commented on services/ELK/ELK-combined-heat-template.yml
> +          - path: /etc/logstash/conf.d/logstash.conf
Yes, adding a reference document to add in logstash configuration file.

2023-12-28 05:47 UTC, pranav79 commented on services/ELK/ELK-combined-heat-template.yml
> +outputs:
Updated with bootstrap password for ELK.

2023-12-28 06:09 UTC, pranav79 commented on services/ELK/ELK-combined-heat-template.yml
> +        template: http://host:5601
Should we change this to a specific port instead of the regular port 5601?

2023-12-28 06:10 UTC, pranav79 commented
Updated on the comments raised from separate templates and also on the combined ELK Template.

2024-01-11 07:12 UTC, jain-rajat reviewed
You can use parameterGroup in heat to order parameters in your way. Otherwise it will be random.
Also - This parametergroup thing works well in Horizon but not in fleio. In fleio it will be in 2024.01 but good to keep it now.
Also test it well!

2024-03-07 05:27 UTC, pranav79 commented on services/ELK/ELK-combined-heat-template.yml
> +  OpenStack Heat template for deploying the ELK Stack (Elasticsearch, Logstash, Kibana).
Updated.

2024-04-18 08:02 UTC, AndreasDilworth commented on services/ELK/logstash-heat-template.yml
> +          delete_on_termination: true
I don't see that this has been fixed (also check services/lamp-loadbalanced/lamp-loadbalanced-en.yaml for example of backup through Mistral).

2024-04-18 08:03 UTC, AndreasDilworth commented on services/ELK/ELK-combined-heat-template.yml
> +        template: http://host:5601
I seem to have missed "port 80"

2024-04-18 08:04 UTC, AndreasDilworth commented on services/ELK/ELK-combined-heat-template.yml
> +    default: europe-se-1a
The custom constraint should be added in our backend. Does not need to be added to this repository as it does not apply to vanilla HEAT.

2024-04-18 08:07 UTC, AndreasDilworth requested changes
There's still a some unresolved comments, please review all open comments.

2024-04-24 05:54 UTC, pranav79 commented
> Member

Yes, they have

2024-04-24 05:54 UTC, closed without merging

2024-04-24 05:58 UTC, pranav79 commented on services/ELK/ELK-combined-heat-template.yml
> +            until curl -s -XGET "http://{ get_attr: [elasticsearchserver, first_address, ''] }:9200" | grep -q '\"status\":\"green\"'; do
Updated with wait_handle condition